# Generated by Django 5.0.3 on 2024-03-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "namb",
                    models.CharField(
                        blank=True,
                        max_length=35,
                        null=True,
                        verbose_name="номер договора",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="ФИО/Наименование"
                    ),
                ),
                ("fase", models.CharField(max_length=50, verbose_name="физ./юрлицо")),
                ("status", models.CharField(max_length=50, verbose_name="Статус")),
                (
                    "id_adress",
                    models.CharField(max_length=150, verbose_name="id адреса"),
                ),
            ],
            options={
                "verbose_name": "Договор",
                "verbose_name_plural": "Договора",
            },
        ),
    ]
