# Generated by Django 5.0.3 on 2024-03-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tmpk", "0002_adres"),
    ]

    operations = [
        migrations.CreateModel(
            name="Many",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("man", models.IntegerField(max_length=10, verbose_name="Сумма")),
                (
                    "data_op",
                    models.DateField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Дата начала действия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приход денежных средств",
                "verbose_name_plural": "Приходы денежных средств",
            },
        ),
        migrations.CreateModel(
            name="Prase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Тариф наименование"),
                ),
                ("cost", models.IntegerField(max_length=10, verbose_name="Стоимость")),
                (
                    "data_n",
                    models.DateField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Дата начала действия",
                    ),
                ),
                (
                    "data_f",
                    models.DateField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Дата окончания действия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф",
                "verbose_name_plural": "Тарифы",
            },
        ),
        migrations.AlterModelOptions(
            name="adres",
            options={"verbose_name": "Адрес", "verbose_name_plural": "Адреса"},
        ),
    ]
